# Generated by Django 4.2.5 on 2023-09-08 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_client', '0001_initial'),
        ('app_produit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Livrer', 'Livrer'), ('Nom_livrer', 'Nom_livrer'), ('En_attenta', 'En_attente')], max_length=100)),
                ('date_cmde', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_client.client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_produit.produit')),
            ],
        ),
    ]
