# Generated by Django 4.2.5 on 2023-09-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cmde', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('Livrer', 'Livrer'), ('Non_livrer', 'Non_livrer')], max_length=100),
        ),
    ]
