# Generated by Django 4.2.5 on 2023-09-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cmde', '0002_commande_quantite_alter_commande_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='paye',
            field=models.BooleanField(default=False),
        ),
    ]
