# Generated by Django 4.2.5 on 2023-09-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_produit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
