# Generated by Django 4.2.5 on 2023-09-18 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_cmde', '0003_commande_paye'),
        ('app_client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_facture', models.CharField(choices=[('R', 'Recu'), ('P', 'Performancefacture'), ('F', 'Facture')], max_length=1)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('date_facture', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_client.client')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cmde.commande')),
            ],
        ),
    ]
